def displayMenu() -> None:
    print(f"\n\nLibz - A Library Management System".center(80))
    print("\nChoose Options\n")
    print("\t1. View Books' Details")
    print("\t2. View Users' Details")
    print("\t3. Search Book")
    print("\t4. Search User")
    print("\t5. Lending Book")
    print("\t6. Return Book")
    print("\t7. Add New Book")
    print("\t8. Add New User")
    print("\t9. Delete Book")
    print("\t10. Delete User")
    print("\t11. View Lending History")
    print("\t12. View Overdue Books")
    print("\t13. Update Book Information")
    print("\t14. Update User Information")
    print("\t15. Exit")
